install_packages:
	pip install --upgrade pip
		pip install -r packages.txt --target ../

install:
	pip install --upgrade pip
		pip install -r requirements.txt

make all:
	make install_packages
	make install
